[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --themesDir ../.. --gc --minify --templateMetrics --templateMetricsHints --forceSyncStatic"
  
[build.environment]
  HUGO_VERSION = "0.127.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"