# navigation
[[main]]
name = "Events"
url = ""
weight = 1
hasChildren = true

  [[main]]
  weight = 2
  parent = "Events"
  name = "Meetings"
  url = "events/meetings"

  [[main]]
  weight = 1
  parent = "Events"
  name = "Show & Sale"
  url = "blog/show"

[[main]]
name = "About"
url = "about"
weight = 2

[[main]]
name = "Contact"
url = "contact"
weight = 4

[[main]]
name = "Membership"
url = "membership"
weight = 3

[[main]]
name = "Gallery"
url = "gallery"
weight = 5
